<?php

if ($block->isEnabled()) : ?>
    <script>
        require([
            'jquery',
            'atqscrollScript'
        ], function ($) {
            var bodyElem = $('body');
            if ($.data(bodyElem[0], 'mage-atqscrollScript')) {
                bodyElem.atqscrollScript('initialize');
            } else {
                bodyElem.atqscrollScript(<?= $block->getConfig();?>);
            }
        });
    </script>
<?php endif; ?>
